export const FETCHING_GLOBAL_CASES_SUCCESS = 'FETCHING_GLOBAL_CASES_SUCCESS';
export const FETCHING_COUNTRY_CASES_SUCCESS = 'FETCHING_COUNTRY_CASES_SUCCESS';
export const FETCHING_CASES_FAILURE = 'FETCHING_CASES_FAILURE';
export const FETCHING_CASES_REQUEST = 'FETCHING_CASES_REQUEST';

export const FETCHING_GLOBAL_TIMELINE_SUCCESS = 'FETCHING_GLOBAL_TIMELINE_SUCCESS';
export const FETCHING_COUNTRY_TIMELINE_SUCCESS = 'FETCHING_COUNTRY_TIMELINE_SUCCESS';
export const FETCHING_TIMELINE_FAILURE = 'FETCHING_TIMELINE_FAILURE';
export const FETCHING_TIMELINE_REQUEST = 'FETCHING_TIMELINE_REQUEST';

export const TOGGLE_LOCALE_SWITCH = 'TOGGLE_LOCALE_SWITCH';